# Configuration de la connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mon_presence_db
spring.datasource.username=postgres
spring.datasource.password=presence123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=bossikpononisrael@gmail.com
spring.mail.password=vhcxjlpomhoedxni

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=bossikpononisrael@gmail.com
logging.level.org.springframework.security=DEBUG